name: build-matrix
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v4
      
      - name: Configure and build (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DCMAKE_CXX_EXTENSIONS=OFF \
            -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -Werror"
          cmake --build build -j

      - name: Configure and build (Windows MSVC)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -S . -B build -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_CXX_STANDARD=20 ^
            -DCMAKE_CXX_STANDARD_REQUIRED=ON ^
            -DCMAKE_CXX_EXTENSIONS=OFF ^
            -DCMAKE_CXX_FLAGS="/W4 /WX /permissive- /Zc:__cplusplus /EHsc"
          cmake --build build -j
